sonarr:
  server:
    address: ${SERVER_HOST-localhost}
    port: ${SERVER_PORT-8989}
  config:
    ui:
      uiLanguage: 1 # 1 = English, 2 = French, 3 = Spanish...
  rootfolder:
    - name: Series
      path: /data/series
      defaultTags: []
      defaultQualityProfileId: 1
      defaultMetadataProfileId: 1
