apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sonarr.name" . }}-config
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
data:
  config.xml: |
    <Config>
      <BindAddress>*</BindAddress>
      <Port>{{ .Values.sonarr.service.port }}</Port>
      <SslPort>9898</SslPort>
      <EnableSsl>False</EnableSsl>
      <LaunchBrowser>True</LaunchBrowser>
      <ApiKey>{{ include "sonarr.apiKey" . }}</ApiKey>
      <AuthenticationMethod>None</AuthenticationMethod>
      <Branch>master</Branch>
      <LogLevel>info</LogLevel>
      <SslCertPath></SslCertPath>
      <SslCertPassword></SslCertPassword>
      <UrlBase></UrlBase>
      <InstanceName>sonarr</InstanceName>
      <UpdateMechanism>Docker</UpdateMechanism>
      <AnalyticsEnabled>False</AnalyticsEnabled>
    </Config>
