{{- if .Values.sonarr.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sonarr.name" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
  {{- if not (empty .Values.servarr.annotations) }}
  annotations:
    {{- with .Values.servarr.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.sonarr.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if not .Values.sonarr.autoscaling.enabled }}
  replicas: {{ .Values.sonarr.replicas }}
  {{- end }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  revisionHistoryLimit: {{ .Values.servarr.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "sonarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/sonarr/config.yaml") . | sha256sum }}
        {{- with .Values.servarr.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.sonarr.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "sonarr.selectorLabels" . | nindent 8 }}
        {{- with .Values.servarr.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.sonarr.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.sonarr.selectorLabels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "servarr.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "sonarr.priorityClassName" . | nindent 6 }}
      securityContext:
        {{- toYaml .Values.servarr.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.sonarr.terminationGracePeriodSeconds }}
      containers:
        - name: sonarr
          image: {{ printf "%s:%s" .Values.sonarr.image.repository (default "latest" .Values.sonarr.image.tag) | quote }}
          imagePullPolicy: {{ .Values.sonarr.image.pullPolicy }}
          args:
            - -config.file=/etc/loki/config/config.yaml
            - -target={{ .Values.sonarr.targetModule }}
            - -legacy-sonarr-mode=false
            - -common.compactor-grpc-address={{ include "servarr.backendFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:9095
            {{- with .Values.sonarr.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
            - name: http-memberlist
              containerPort: 7946
              protocol: TCP

          env:
            - name: TZ
              value: "{{ .Values.common.timezone | default "UTC" }}"
            {{- with .Values.sonarr.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.sonarr.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.common.containerSecurityContext | nindent 12 }}
          livenessProbe:
            exec:
              command:
              - /usr/bin/env
              - bash
              - -c
              - "curl --fail localhost:{{ include "sonarr.port" . }}/api/v3/system/status?apiKey=`IFS=\> && while
                read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`"
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10

          readinessProbe:
            {{- toYaml .Values.servarr.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/loki/config
            - name: runtime-config
              mountPath: /etc/loki/runtime-config
            - name: tmp
              mountPath: /tmp
            - name: data
              mountPath: /var/loki
            {{- if .Values.enterprise.enabled }}
            - name: license
              mountPath: /etc/loki/license
            {{- end}}
            {{- with .Values.sonarr.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.sonarr.resources | nindent 12 }}
      {{- with .Values.sonarr.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.sonarr.dnsConfig }}
      dnsConfig:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.sonarr.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sonarr.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: data
          emptyDir: {}
        - name: config
          {{- if .Values.servarr.existingSecretForConfig }}
          secret:
            secretName: {{ .Values.servarr.existingSecretForConfig }}
          {{- else }}
          {{- include "servarr.configVolume" . | nindent 10 }}
          {{- end }}
        - name: runtime-config
          configMap:
            name: {{ template "servarr.name" . }}-runtime
        {{- if .Values.enterprise.enabled }}
        - name: license
          secret:
          {{- if .Values.enterprise.useExternalLicense }}
            secretName: {{ .Values.enterprise.externalLicenseName }}
          {{- else }}
            secretName: enterprise-logs-license
          {{- end }}
        {{- end }}
        {{- with .Values.sonarr.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
