# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/bmc.tinkerbell.org/machine_v1alpha1.json
{{- range .Values.workflows }}
---
apiVersion: tinkerbell.org/v1alpha1
kind: Workflow
metadata:
  {{- with .additionalAnnotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- with .additionalLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .name }}
  {{- with .namespace }}
  namespace: {{ . }}
  {{- end }}
  {{- with .finalizers }}
  finalizers:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .templateRef }}
  templateRef: {{ . }}
  {{- end }}
  {{- with .hardwareRef }}
  hardwareRef: {{ . }}
  {{- end }}
  {{- with .hardwareMap }}
  hardwareMap:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}