{{- $componentKeys := list "sonarr" "radarr" "lidarr" "readarr" "prowlarr" }}
{{- $apiKeys := dict }}
{{- $components := pick .Values "sonarr" "radarr" "lidarr" "readarr" "prowlarr" | default dict }}
{{- range $key, $val := $components }}
{{- if $val.enabled }}
{{- $_ := set $apiKeys $key ($val.apiKey | default (uuidv4 | replace "-" "")) }}
{{- else if ne $key "prowlarr" }}
{{- $_ := unset $components $key}}
{{- end }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
data:
{{- range $key, $val := pick .Values "sonarr" "radarr" "lidarr" "readarr" "prowlarr" | default dict }}
  {{ $key }}-config.xml: |-
    <Config>
      <BindAddress>*</BindAddress>
      <Port>{{ $val.service.port }}</Port>
      <SslPort>9898</SslPort>
      <EnableSsl>False</EnableSsl>
      <LaunchBrowser>False</LaunchBrowser>
      <ApiKey>{{ get $apiKeys $key }}</ApiKey>
      <AuthenticationMethod>External</AuthenticationMethod>
      <Branch>main</Branch>
      <LogLevel>info</LogLevel>
      <SslCertPath></SslCertPath>
      <SslCertPassword></SslCertPassword>
      <UrlBase></UrlBase>
      <InstanceName>{{ $key }}</InstanceName>
      <UpdateMechanism>Docker</UpdateMechanism>
      <UpdateAutomatically>False</UpdateAutomatically>
      <AnalyticsEnabled>False</AnalyticsEnabled>
{{- if and $val.postgresql (default false $val.postgresql.enabled) }}
  {{- with $val.postgresql }}
      <PostgresUser>{{ default $key .username }}</PostgresUser>
      <PostgresPassword>{{ default "admin" .password }}</PostgresPassword>
      <PostgresPort>{{ default "5432" .port }}</PostgresPort>
      <PostgresHost>{{ default $key .host }}</PostgresHost>
      <PostgresMainDb>{{ default $key .database }}</PostgresMainDb>
      <PostgresLogDb>{{ default (printf "%s_log" $key) .logdb }}</PostgresLogDb>
  {{- end }}
{{- end }}
    </Config>
{{ end -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flemmarr-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: flemmarr
data:
  config.yml: |
    {{- range $key, $val := pick .Values "sonarr" "radarr" | default dict -}}
    {{- list $val $key | include "servarr.flemmarrSection" | indent 4 }}
    {{ end -}}
