kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "servarr.name" . }}-downloads
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "20Gi"
  {{- if .Values.global.persistence.storageClass }}
  storageClassName: {{ .Values.global.persistence.storageClass | quote }}
  {{- end }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "servarr.name" . }}-media
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "servarr.labels" . | nindent 4 }}
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "20Gi"
  {{- if .Values.global.persistence.storageClass }}
  storageClassName: {{ .Values.global.persistence.storageClass | quote }}
  {{- end }}
