---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "qbittorrent.name" . }}-config
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
data:
  qBittorrent.conf: |
    {{- include "qbittorrent.configData" . | nindent 4 }}

#    [AutoRun]
#    enabled=false
#    program=
#
#    [Locking]
#    locked=false
#
#    [BitTorrent]
#    Session\DefaultSavePath=/downloads/
#    Session\Port=6881
#    Session\QueueingSystemEnabled=true
#    Session\TempPath=/downloads/
#
#    [LegalNotice]
#    Accepted=true
#
#    [Meta]
#    MigrationVersion=4
#
#    [Network]
#    PortForwardingEnabled=false
#
#    [Preferences]
#    Connection\PortRangeMin=6881
#    Connection\UPnP=false
#    Downloads\SavePath=/downloads/
#    Downloads\TempPath=/downloads/
#    WebUI\Address=*
#    WebUI\Port={{ include "qbittorrent.port" . }}
#    WebUI\ServerDomains=*
#    WebUI\AlternativeUIEnabled=true
#    WebUI\RootFolder=/data/vuetorrent
#    WebUI\HostHeaderValidation=false
#    WebUI\CSRFProtection=false
#    WebUI\CustomHTTPHeadersEnabled=false
#    WebUI\AuthSubnetWhitelistEnabled=true
#    WebUI\AuthSubnetWhitelist=10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 0.0.0.0/0
