---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sonarr.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "qbittorrent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/qbittorrent/config.yaml") . | sha256sum }}
      labels:
        {{- include "qbittorrent.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "servarr.serviceAccountName" . }}
      {{- if or .Values.common.priorityClassName .Values.qbittorrent.priorityClassName }}
      priorityClassName: {{ coalesce .Values.common.priorityClassName .Values.qbittorrent.priorityClassName | quote }}
      {{- end }}
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      {{- if .Values.qbittorrent.customWebUi.enabled }}
      {{- with .Values.qbittorrent.customWebUi }}
      initContainers:
        - name: {{ default "download-custom-webui" .name }}
          image: {{ default "busybox:latest" .image }}
          command: {{ default "[\"sh\", \"-c\"]" .command }}
          args:
          {{- if .args }}
            {{ toYaml .args | nindent 12 }}
          {{- else }}
            - wget -qO- https://github.com/WDaan/VueTorrent/releases/download/v1.6.1/vuetorrent.zip | unzip - -d /data
          {{- end }}
          volumeMounts:
            - mountPath: /data
              name: data
      {{- end }}
      {{- end }}
      containers:
        - name: qbittorrent
          image: "ghcr.io/k8s-at-home/qbittorrent:v4.4.2"
          imagePullPolicy: IfNotPresent
          securityContext:
            fsGroup: 0
            runAsGroup: 0
            runAsUser: 0
          env:
            - name: PGID
              value: "0"
            - name: PUID
              value: "0"
            - name: TZ
              value: Etc/UTC
            - name: WEBUI_PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 9022
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config/qBittorrent/qBittorrent.conf
              subPath: qBittorrent.conf
            - name: data
              mountPath: /data
            - name: downloads
              mountPath: /downloads
            - name: media
              mountPath: /media

        - name: exporter
          image: esanchezm/prometheus-qbittorrent-exporter:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: QBITTORRENT_HOST
              value: http://localhost
            - name: QBITTORRENT_PORT
              value: "8080"
            - name: QBITTORRENT_USER
              value: admin
            - name: QBITTORRENT_PASS
              value: adminadmin
            - name: EXPORTER_PORT
              value: "9022"
            - name: EXPORTER_LOG_LEVEL
              value: ERROR
          ports:
          - containerPort: 9022
            name: metrics
        {{- if .Values.qbittorrent.vpn.enabled }}
        {{- with .Values.qbittorrent.vpn }}
        - name: {{ default "vpn" .name }}
          image: {{ default "qmcgaw/gluetun:latest" .image }}
          env:
            - name: TZ
              value: UTC
            {{- with .env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ default 8000 .port }}
              name: control-port
              protocol: TCP
          {{- with .securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "qbittorrent.name" . }}-config
            items:
              - key: "qBittorrent.conf"
                path: "qBittorrent.conf"
        - name: data
          persistentVolumeClaim:
            claimName: qbittorrent-data
        - name: downloads
          persistentVolumeClaim:
            claimName: qbittorrent-downloads
        - name: media
          persistentVolumeClaim:
            claimName: qbittorrent-media
