kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "qbittorrent.name" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "50Mi"
  {{- if .Values.global.persistence.storageClass }}
  storageClassName: {{ .Values.global.persistence.storageClass | quote }}
  {{- end }}
