apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 9022
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "qbittorrent.selectorLabels" . | nindent 4 }}