apiVersion: v1
kind: ConfigMap
metadata:
  name: ironic
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "baremetal-operator.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  {{- range $key, $value := .Values.ironic.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
