{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namePrefix }}{{ .Values.webhook.service.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.webhook.service.port }}
      targetPort: {{ .Values.webhook.service.targetPort }}
      protocol: TCP
  selector:
    control-plane: controller-manager
    webhook: metal3-io-v1alpha1-baremetalhost
{{- end }}
