{{- if and (not .Values.account.accountSecret) (.Values.account.username) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "factorio.fullname" . }}-account
  labels:
    app: {{ template "factorio.fullname" . }}
    chart: {{ template "factorio.fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  username: {{ .Values.account.username | b64enc }}
  {{- if .Values.account.password }}
  password: {{ .Values.account.password | b64enc }}
  {{- end }}
  {{- if .Values.account.token }}
  token: {{.Values.account.token | b64enc }}
  {{- end }}
{{- end }}
