{{- if and (not .Values.rcon.passwordSecret) (.Values.rcon.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "factorio.fullname" . }}-rcon
  labels:
    app: {{ template "factorio.fullname" . }}
    chart: {{ template "factorio.fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  rconpw: |
  {{ .Values.rcon.password | b64enc | indent 4 }}
{{- end }}
