{{- if .Values.cloudProvider.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-vip.name" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
data:
  cidr-global: {{ .Values.cloudProvider.cidr }}
{{- end}}