{{- if .Values.cloudProvider.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-vip.name" . }}-cloud-provider
  namespace: {{ .Release.Namespace | default "kube-system" }}
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      {{- include "kube-vip.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kube-vip.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - command:
          - /kube-vip-cloud-provider
          - --leader-elect-resource-name=kube-vip-cloud-controller
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        name: {{ include "kube-vip.name" . }}-cloud-provider
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        {{- with .Values.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kube-vip.name" . }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end}}
