{{- $labels := include "external-secrets-stack.labels" . -}}
{{- range $ns := without (values .Values.tags) "distributed" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $ns | quote}}
  labels:
    {{- $labels | nindent 4 }}
{{- end }}
